#!/bin/sh

set -e

PROMPT=$(cat "${HOME}/.prompts/summarize-diff.poml")
TRUNK="$(git symbolic-ref refs/remotes/origin/HEAD --short)"

# Ignores tests because they can be exceptionally noisy in diffs
# AI_SUMMARY="$(git diff $TRUNK -- . ':!*tests*' | clai --chat-model ollama:gemma3:4b -r q "$PROMPT")"
DIFF="$(git simple-diff "$@")"

if [ -z "$DIFF" ]; then
  echo "Skipping, diff is empty..." >&2
  exit 1
fi

AI_SUMMARY="$(echo "$DIFF" | claude --output-format text -p "$PROMPT")"
echo "$AI_SUMMARY"
