ssh:
  hosts:
    - name: dns
      op_id: tm5resrpeemg7ttfqzlompeswu
    - name: low
      op_id: ckf2rbsccbycp7rqayvkhvqbsq
    - name: linux-gpu
      op_id: mnnz4e7mnqvut2ia5s45klrbx4
    - name: deskpi
      op_id: dd476nm7gjoh3o4uh3xgqlqznm
    - name: pikvm
      op_id: kj5e77g63x5u6czm7u7jm7pfna